Repository git-gurus-itu-devops/itu-minitwit, pull requests merged in 2024-03, with the labels that each got.

#29 Statuscode 404 when user not found
  myapp.rb
  simapi/sim_api.rb
Labels: bug

#31 Set statuscode to 204 endpoints
  Makefile
  simapi/sim_api.rb
Labels: bug

#34 Migrate to managed PSQL database
  .github/workflows/continous-deployment.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  Makefile
  README.md
  Rakefile
  Vagrantfile
  control.sh
  db/migrate/20240212100229_add_password_digest_to_user.rb
  db/migrate/20240301114515_add_initial_schema.rb
  db/schema.rb
  db/seeds.rb
  docker-compose-tests.yaml
  models/follower.rb
  models/message.rb
  models/user.rb
  myapp.rb
  remote_files/deploy.sh
  remote_files/docker-compose.yml
  simapi/sim_api.rb
  tasks/console.rake
  tasks/pg_migrate.rake
  views/timeline.erb
Labels: infrastructure

#37 Fix non-idempotent GitHub Actions
  .github/workflows/continous-deployment.yml
  docker-compose-tests.yaml
Labels: help wanted, infrastructure, testing

#41 Add new relic gem and inject license key
  .github/workflows/continous-deployment.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  Vagrantfile
  myapp.rb
  newrelic.yml
  remote_files/deploy.sh
  remote_files/docker-compose.yml
  simapi/sim_api.rb
Labels: infrastructure

#42 Add GH public keys as authorized SSH keys
  Vagrantfile
Labels: infrastructure

#44 Adds staging env
  .github/workflows/continous-deployment.yml
  .github/workflows/deploy-staging.yml
  Vagrantfile
  myapp.rb
  newrelic.yml
  remote_files/deploy.sh
  remote_files/docker-compose.yml
  simapi/sim_api.rb
Labels: enhancement, infrastructure

#47 Set up prod-deploy and use sha for testing
  .github/workflows/automatic-testing.yml
  .github/workflows/deploy-prod.yml
  docker-compose-api-test.yaml
  docker-compose-tests.yaml
Labels: bug, infrastructure
